# Generated by Django 3.1 on 2020-08-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmodel',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='magazin/img'),
        ),
    ]
