# Generated by Django 3.1 on 2020-08-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazin', '0002_goodsmodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmodel',
            name='description',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
