# Generated by Django 3.1 on 2020-08-27 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('magazin', '0004_auto_20200824_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsmodel',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='magazin\\img'),
        ),
        migrations.CreateModel(
            name='UserProfileRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_register',
            },
        ),
    ]
